name: GitHub Metrics

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

permissions:
  contents: write   # ðŸ”´ VACÄ°B

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          user: Tagforaz
          token: ${{ secrets.METRICS_TOKEN }}

          # ðŸ”´ SVG adÄ±
          filename: github-metrics.svg

          # É™sas hissÉ™
          base: header, activity, repositories

          # commit & activity
          plugin_activity: yes
          plugin_activity_limit: 0
          plugin_activity_days: 365
          plugin_activity_filter: all
